server:
  port: 8080
  servlet:
    context-path: /hotel
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: board2024_boot_jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.26.66:12506/HotelReserv?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
#    url: jdbc:mysql:localhost:8080/HotelReserv?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: kopo
#    password: 1234
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate.dialect: org.hibernate.dialect.MySQLDialect

#  # 나중에 모든 기능 만들면 없애기
#  server:
#    error:
#      whitelabel:
#        enabled: false  # 기본 Whitelabel Error Page 비활성화
#      path: /error
#      include-exception: true  # 필요에 따라 예외 메시지를 포함할 수 있음

logging:
  level:
    org.springframework.security: DEBUG